# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# OpenAI-Compatible Ollama Configuration (Recommended)
# This approach uses Ollama's built-in OpenAI-compatible API endpoint

general:
  use_uvloop: true
  telemetry:
    logging:
      console:
        _type: console
        level: WARN
      file:
        _type: file
        path: /tmp/ollama_example.log
        level: DEBUG

functions:
  email_phishing_analyzer:
    _type: email_phishing_analyzer
    llm: ollama_llm
    prompt: |
      Examine the following email content and determine if it exhibits signs of malicious intent.
      Look for any suspicious signals that may indicate phishing, such as requests for personal 
      information or suspicious tone.

      Email content:
      {body}

      Return your findings as a JSON object with these fields:
      - is_likely_phishing: (boolean) true if phishing is suspected
      - explanation: (string) detailed explanation of your reasoning

llms:
  ollama_llm:
    _type: openai                          # Use OpenAI provider
    base_url: http://192.168.8.21:11434/v1 # Ollama server with /v1 suffix
    api_key: "not-needed"                  # Ollama doesn't require API key
    model_name: gpt-oss:20b                 # Your Ollama model name
    temperature: 0.0
    max_tokens: 512
    
  ollama_rag_eval_llm:
    _type: openai
    base_url: http://192.168.8.21:11434/v1
    api_key: "not-needed"
    model_name: gpt-oss:20b
    max_tokens: 8
    
  ollama_trajectory_eval_llm:
    _type: openai
    base_url: http://192.168.8.21:11434/v1
    api_key: "not-needed"
    model_name: gpt-oss:20b
    temperature: 0.0
    max_tokens: 1024

workflow:
  _type: react_agent
  tool_names:
    - email_phishing_analyzer
  llm_name: ollama_llm
  verbose: true
  parse_agent_response_max_retries: 3

eval:
  general:
    output_dir: ./.tmp/eval/ollama_example
    verbose: true
    dataset:
        _type: csv
        file_path: examples/evaluation_and_profiling/email_phishing_analyzer/data/smaller_test.csv
        id_key: "subject"
        structure:
          question_key: body
          answer_key: label

    profiler:
        token_uniqueness_forecast: true
        workflow_runtime_forecast: true
        compute_llm_metrics: true
        csv_exclude_io_text: true
        prompt_caching_prefixes:
          enable: true
          min_frequency: 0.1
        bottleneck_analysis:
          enable_nested_stack: true
        concurrency_spike_analysis:
          enable: true
          spike_threshold: 7

  evaluators:
    rag_accuracy:
      _type: ragas
      metric: AnswerAccuracy
      llm_name: ollama_rag_eval_llm
    rag_groundedness:
      _type: ragas
      metric: ResponseGroundedness
      llm_name: ollama_rag_eval_llm
    rag_relevance:
      _type: ragas
      metric: ContextRelevance
      llm_name: ollama_rag_eval_llm
    trajectory_accuracy:
      _type: trajectory
      llm_name: ollama_trajectory_eval_llm