const { models } = require('../models/index');

const seedNotifications = async (organizationId, userId) => {
  const notificationsData = [
    {
      id: '550e8400-e29b-41d4-a716-446655440040',
      title: 'Critical Alert: Malware Detected',
      message: 'Suspicious PowerShell activity detected on DC-SERVER-01. Immediate action required to prevent system compromise.',
      type: 'alert',
      priority: 'critical',
      isRead: false,
      actionRequired: true,
      relatedId: '550e8400-e29b-41d4-a716-446655440020',
      relatedType: 'alert',
      userId,
      organizationId,
      sourceSystem: 'Windows Defender ATP',
      notificationChannel: 'web',
      notificationSettings: {
        urgency: 'immediate',
        escalation: true,
        autoContainment: false
      },
      createdAt: new Date('2024-01-15T10:30:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440041',
      title: 'Incident Update: Network Intrusion Contained',
      message: 'The network intrusion incident INC-2024-001 has been successfully contained. Firewall rules updated to block malicious traffic.',
      type: 'incident',
      priority: 'high',
      isRead: true,
      actionRequired: false,
      relatedId: '550e8400-e29b-41d4-a716-446655440031',
      relatedType: 'incident',
      userId,
      organizationId,
      sourceSystem: 'SOC Platform',
      notificationChannel: 'web',
      readAt: new Date('2024-01-15T10:05:00Z'),
      notificationSettings: {
        resolution: 'contained',
        followUp: false
      },
      createdAt: new Date('2024-01-15T10:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440042',
      title: 'System Maintenance: Database Server Restart',
      message: 'DB-SERVER-01 will undergo scheduled maintenance tonight at 2:00 AM EST. Expected downtime: 30 minutes.',
      type: 'system',
      priority: 'medium',
      isRead: false,
      actionRequired: false,
      relatedId: '550e8400-e29b-41d4-a716-446655440014',
      relatedType: 'asset',
      userId,
      organizationId,
      sourceSystem: 'System Monitor',
      notificationChannel: 'web',
      notificationSettings: {
        maintenanceWindow: '02:00-03:00 EST',
        estimatedDowntime: 30,
        affectedServices: ['database', 'reports']
      },
      createdAt: new Date('2024-01-15T14:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440043',
      title: 'Security Update: New Threat Intelligence',
      message: 'New IOCs have been added from MISP feed. 15 new malicious domains and 8 IP addresses now being monitored.',
      type: 'security',
      priority: 'low',
      isRead: true,
      actionRequired: false,
      userId,
      organizationId,
      sourceSystem: 'MISP Feed',
      notificationChannel: 'web',
      readAt: new Date('2024-01-15T08:15:00Z'),
      notificationSettings: {
        feedSource: 'MISP',
        newDomains: 15,
        newIPs: 8,
        autoUpdate: true
      },
      createdAt: new Date('2024-01-15T08:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440044',
      title: 'Data Breach Alert: Sensitive Data Accessed',
      message: 'Unauthorized access to customer database detected. 50,000 records potentially compromised. Legal and compliance teams notified.',
      type: 'alert',
      priority: 'critical',
      isRead: false,
      actionRequired: true,
      relatedId: '550e8400-e29b-41d4-a716-446655440032',
      relatedType: 'incident',
      userId,
      organizationId,
      sourceSystem: 'Database Audit',
      notificationChannel: 'email',
      notificationSettings: {
        severity: 'critical',
        recordsAffected: 50000,
        legalNotified: true,
        complianceNotified: true,
        breachType: 'unauthorized_access'
      },
      createdAt: new Date('2024-01-15T08:30:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440045',
      title: 'Weekly Security Report Available',
      message: 'Your weekly security summary report is ready for review. This week: 127 alerts processed, 3 incidents resolved.',
      type: 'info',
      priority: 'low',
      isRead: false,
      actionRequired: false,
      userId,
      organizationId,
      sourceSystem: 'Report Generator',
      notificationChannel: 'web',
      notificationSettings: {
        reportType: 'weekly_summary',
        alertsProcessed: 127,
        incidentsResolved: 3,
        period: '2024-01-08 to 2024-01-15'
      },
      createdAt: new Date('2024-01-15T09:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440046',
      title: 'Failed Login Attempts: Account Lockout',
      message: 'Multiple failed login attempts detected for administrator account. Account has been temporarily locked for security.',
      type: 'security',
      priority: 'high',
      isRead: true,
      actionRequired: false,
      relatedId: '550e8400-e29b-41d4-a716-446655440022',
      relatedType: 'alert',
      userId,
      organizationId,
      sourceSystem: 'Authentication System',
      notificationChannel: 'web',
      readAt: new Date('2024-01-15T11:20:00Z'),
      notificationSettings: {
        account: 'administrator',
        failedAttempts: 5,
        lockoutDuration: 3600,
        sourceIP: '203.0.113.45'
      },
      createdAt: new Date('2024-01-15T11:15:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440047',
      title: 'Vulnerability Patched: Apache Struts Updated',
      message: 'Critical vulnerability CVE-2023-50164 has been successfully patched on WEB-SERVER-01. System is no longer at risk.',
      type: 'security',
      priority: 'medium',
      isRead: true,
      actionRequired: false,
      relatedId: '550e8400-e29b-41d4-a716-446655440024',
      relatedType: 'alert',
      userId,
      organizationId,
      sourceSystem: 'Patch Management',
      notificationChannel: 'web',
      readAt: new Date('2024-01-14T18:30:00Z'),
      notificationSettings: {
        cve: 'CVE-2023-50164',
        severity: 'critical',
        affectedSystem: 'WEB-SERVER-01',
        patchStatus: 'completed',
        riskReduction: 'high'
      },
      createdAt: new Date('2024-01-14T18:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440048',
      title: 'AI Agent Update: SOC Analyst Performance',
      message: 'SOC-ANALYST-01 has improved its accuracy to 94.5% this week. False positive rate reduced by 15% compared to last week.',
      type: 'info',
      priority: 'low',
      isRead: false,
      actionRequired: false,
      userId,
      organizationId,
      sourceSystem: 'AI Management',
      notificationChannel: 'web',
      notificationSettings: {
        agentName: 'SOC-ANALYST-01',
        accuracy: 94.5,
        falsePositiveReduction: 15,
        period: 'weekly',
        performanceTrend: 'improving'
      },
      createdAt: new Date('2024-01-15T12:00:00Z'),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440049',
      title: 'Compliance Alert: GDPR Assessment Due',
      message: 'Annual GDPR compliance assessment is due in 30 days. Please review data processing activities and update documentation.',
      type: 'info',
      priority: 'medium',
      isRead: false,
      actionRequired: true,
      userId,
      organizationId,
      sourceSystem: 'Compliance Monitor',
      notificationChannel: 'web',
      notificationSettings: {
        assessmentType: 'GDPR Annual',
        daysRemaining: 30,
        requirements: ['data_mapping', 'privacy_policy_review', 'consent_audit'],
        assignedTo: 'compliance_team'
      },
      createdAt: new Date('2024-01-15T13:00:00Z'),
      expiresAt: new Date('2024-02-15T13:00:00Z'),
    },
  ];

  const notifications = await models.Notification.bulkCreate(notificationsData, {
    returning: true,
  });

  return notifications;
};

module.exports = { seedNotifications };