# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Simplified NAT Configuration for troubleshooting with calculation support
# Based on working ollama_provider/examples/config_ollama_simple.yml
# Uses built-in code_execution tool for calculations and virustotal_analyzer

functions:
  code_execution:
    _type: code_execution
  current_datetime:
    _type: current_datetime
  virustotal_analyzer:
    _type: virustotal_analyzer
    llm_name: ollama_llm
    offline_mode: false
    api_key: "${VIRUSTOTAL_API_KEY}"
    base_url: "https://www.virustotal.com/api/v3"
    rate_limit: 4

llms:
  ollama_llm:
    _type: ollama
    base_url: "${LLM_BASE_URL}"
    model: "gpt-oss:20b"
    temperature: 0.1

workflow:
  _type: tool_calling_agent
  tool_names: [code_execution, current_datetime, virustotal_analyzer]
  llm_name: ollama_llm
  verbose: true
  handle_tool_errors: true
  max_iterations: 15